services:
  - type: web
    name: q-less-api
    runtime: docker
    plan: free
    region: frankfurt
    dockerContext: backend
    dockerfilePath: backend/Dockerfile
    envVars:
      - key: APP_ENV
        value: production
      - key: DATABASE_URL
        scope: secret
      - key: AT_SMS_MODE
        value: mock
      - key: AFRICASTALKING_USERNAME
        value: sandbox
      - key: AFRICASTALKING_API_KEY
        scope: secret
      - key: AFRICASTALKING_SENDER_ID
        value: QLess
      - key: APPROACHING_THRESHOLD
        value: "2"
      - key: CORS_ORIGINS
        value: "*"

  - type: web
    name: q-less-staff
    runtime: docker
    plan: free
    region: frankfurt
    dockerContext: frontend
    dockerfilePath: frontend/Dockerfile
    envVars:
      - key: NEXT_PUBLIC_API_URL
        value: https://q-less-api.onrender.com
